// type GenreCollection = {
//   [key: string]: string;
//   rice: string;
//   ramen: string;
//   soba: string;
//   pan: string;
// };
// const GENRE_COLLECTION: GenreCollection = {
//   rice: "ご飯",
//   ramen: "ラーメン",
//   soba: "そば",
//   pan: "パン",
// };
// const [rice, ramen, soba, pasta, pan] = ["ご飯物", "ラーメン", "そば", "パン"];

const GENRE_COLLECTION = [
  /* 0 */ { label: "rice", value: "ご飯", checked: true },
  /* 1 */ { label: "noodle", value: "麺", checked: true },
  /* 2 */ { label: "soba", value: "そば", checked: false },
  /* 3 */ { label: "pan", value: "パン・カフェ", checked: false },
  /* 4 */ { label: "liquor", value: "居酒屋", checked: false },
  /* 5 */ { label: "all", value: "食べ放題", checked: false },
];

const PRICE_COLLECTION = [
  /* 0 */ { label: "reasonable", value: "リーズナブル", checked: true },
  /* 1 */ { label: "luxury", value: "特別な時に", checked: false },
];

const TIME_COLLECTION = [
  /* 0 */ { label: "currently", value: "現在営業中", checked: true },
  /* 1 */ { label: "lunch", value: "ランチ", checked: true },
  /* 2 */ { label: "dinner", value: "ディナー", checked: true },
];

function changeTime(time: number) {
  const hour: number = Math.floor(time / 100);
  const minute: number = time - Math.floor(time / 100) * 100;

  let minute_string: string = "?";

  if (minute > 59 || minute < 0) minute_string = "?";
  else if (minute < 10) minute_string = "0" + minute;
  else minute_string = minute.toString();

  return hour + ":" + minute_string;
}

// Name:      店名、市内に2店舗以上ある場合支店名(地域名)も書く
// Id:        パス
// Genre:     ご飯物、麺、そば、パン [rice, noodle, soba, pan]
// Score:     [味,量,値段]
// 味:         1:まずい 2:家庭的・生協 3:外食にしては普通 4:チェーン店レベル 5:毎日食べたい 6:最上級
// 量:         1000円でどれくらいの腹を満たせるか、1:50-60 2:60-70 3:70-80 4:80-90 5:90-120
// 値段:       1:2000円以上 2:1500円-2000円 3:1000円-1500円 4:700円-1000円 5:700円以下
//
// Cycle:     自転車で何分か
// Opened:    開店時間(ラストオーダーを閉店時間とする)
// OpenedDay: [月,火,水,木,金,土,日]
// Map:       GoogleMapの検索ワード
// Pay:       [PayPay,クレカ,電子マネー]
// Parking:   [駐車場,駐輪場]
// Coupon:    Coupon[0]:クーポンがあるか、その詳細 / Coupon[1]:それに付随するリンク

const List = [
  {
    Name: "でんでん",
    Id: "denden",
    Genre: [0],
    Score: [4, 5, 3],
    Distance: 1000,
    Opened: [1130, 1430, 1730, 2200],
    OpenedDay: [true, true, true, true, true, true, false],
    Map: "でんでん",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["Twitterフォローで選べるクーポン", " https://x.com/dendenreiji"],
  },
  {
    Name: "満月や",
    Id: "mangetsuya",
    Genre: [0],
    Score: [4, 4, 3],
    Distance: 1100,
    Opened: [1130, 1500, 1700, 2200],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "満月や",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "メーヤウ桐",
    Id: "meyau_kiri",
    Genre: [0],
    Score: [4, 5, 3],
    Distance: 900,
    Opened: [1130, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "メーヤウ 桐店",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "メーヤウ信大前",
    Id: "meyau_shindai",
    Genre: [0],
    Score: [4, 4, 4],
    Distance: 350,
    Opened: [1130, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "メーヤウ 信大前店",
    Pay: [false, false, false],
    Parking: [false, false],
    Coupon: ["なし", ""],
  },
  {
    Name: "麺匠佐蔵",
    Id: "menshosakura",
    Genre: [1],
    Score: [6, 5, 3],
    Distance: 2800,
    Opened: [1130, 1500, 1730, 2200],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "麺匠佐蔵",
    Pay: [false, false, false],
    Parking: [true, false],
    Coupon: ["なし", ""],
  },
  {
    Name: "がったぼうず",
    Id: "gattabozu",
    Genre: [1],
    Score: [5, 5, 4],
    Distance: 1400,
    Opened: [1100, 1500, 1730, 2300],
    OpenedDay: [true, true, true, false, true, true, true],
    Map: "がったぼうず",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "そらや",
    Id: "soraya",
    Genre: [1],
    Score: [5, 4, 3],
    Distance: 800,
    Opened: [1100, 1430, 1700, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "札幌らーめん そらや",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "がねいしゃ",
    Id: "ganeisha",
    Genre: [0],
    Score: [5, 3, 4],
    Distance: 1700,
    Opened: [1130, 1400, 1800, 2200],
    OpenedDay: [false, true, true, true, true, true, false],
    Map: "がねいしゃ",
    Pay: [true, false, false],
    Parking: [false, false],
    Coupon: ["なし", ""],
  },
  {
    Name: "龍華楼",
    Id: "ryukaro",
    Genre: [0, 1],
    Score: [3, 5, 4],
    Distance: 650,
    Opened: [1100, 1430, 1700, 2300],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "龍華楼",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "麺51",
    Id: "menkoi",
    Genre: [1],
    Score: [4, 5, 4],
    Distance: 650,
    Opened: [1130, 1430, 1730, 2130],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "麺51",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: [
      "毎月1の付く日は麺の大盛り変更無料・毎月5の付く日はトッピングサービス・毎月15日は麺の大盛り変更orトッピングサービス",
      "https://x.com/men_51_",
    ],
  },
  {
    Name: "おおぼし桐",
    Id: "oboshi_kiri",
    Genre: [1],
    Score: [4, 4, 4],
    Distance: 900,
    Opened: [1100, 1500, 1730, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "おおぼし 松本桐店",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["学生証提示で麺大盛り無料", ""],
  },
  {
    Name: "Ecru",
    Id: "ecru",
    Genre: [3],
    Score: [5, 3, 5],
    Distance: 1100,
    Opened: [730, 1800],
    OpenedDay: [false, true, true, true, true, true, false],
    Map: "パン焼き工房エクリュ",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "紅葉",
    Id: "koyo",
    Genre: [0, 1],
    Score: [4, 4, 4],
    Distance: 1600,
    Opened: [1100, 1430, 1700, 2300],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "紅葉 松本市 中華",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "潮騒",
    Id: "shiosai",
    Genre: [0],
    Score: [4, 4, 3],
    Distance: 3200,
    Opened: [1130, 1400, 1800, 2130],
    OpenedDay: [true, true, true, true, true, true, false],
    Map: "潮騒",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "どん八",
    Id: "donpachi",
    Genre: [0],
    Score: [4, 5, 3],
    Distance: 3200,
    Opened: [1115, 1500, 1700, 2000],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "海鮮丼どん八 松本駅前本店",
    Pay: [true, true, true],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "河昌",
    Id: "kawasho",
    Genre: [0],
    Score: [5, 4, 3],
    Distance: 1300,
    Opened: [1130, 1330],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "河昌",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "そば打ち楽座",
    Id: "rakuza",
    Genre: [2],
    Score: [5, 4, 4],
    Distance: 1200,
    Opened: [1100, 1900],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "そば打ち楽座",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "ピカドン",
    Id: "pikadon",
    Genre: [0],
    Score: [3, 4, 4],
    Distance: 350,
    Opened: [1130, 1400, 1730, 2100],
    OpenedDay: [true, true, true, true, true, true, false],
    Map: "ピカドン",
    Pay: [false, false, false],
    Parking: [true, false],
    Coupon: ["なし", ""],
  },
  {
    Name: "テンホウ",
    Id: "tenho",
    Genre: [0, 1],
    Score: [4, 4, 3],
    Distance: 550,
    Opened: [1100, 2130],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "テンホウ松本追分店",
    Pay: [true, true, true],
    Parking: [true, true],
    Coupon: ["学生証提示で次回使えるクーポン券", ""],
  },
  {
    Name: "まんま",
    Id: "manma",
    Genre: [0],
    Score: [5, 3, 3],
    Distance: 1500,
    Opened: [1100, 1400],
    OpenedDay: [true, true, true, true, true, true, false],
    Map: "まんま 女鳥羽",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: "",
  },
  {
    Name: "まんぷく亭",
    Id: "manpukutei",
    Genre: [0],
    Score: [4, 4, 4],
    Distance: 1700,
    Opened: [1130, 1430],
    OpenedDay: [false, false, true, true, true, true, true],
    Map: "まんぷく亭 松本",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "ビストロ鬼平",
    Id: "bisutoroonihei",
    Genre: [1],
    Score: [6, 4, 1],
    Distance: 1500,
    Opened: [1200, 1400, 1800, 2045],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "ビストロ鬼平",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "鎌倉パスタ",
    Id: "kamakurapasta",
    Genre: [1],
    Score: [4, 4, 2],
    Distance: 2600,
    Opened: [1100, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "鎌倉パスタ イオンモール松本店",
    Pay: [false, true, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "DOLCE/かつ富",
    Id: "dolce_katsutomi",
    Genre: [0],
    Score: [5, 5, 2],
    Distance: 1200,
    Opened: [1130, 1400, 1800, 2030],
    OpenedDay: [false, false, true, true, true, true, true],
    Map: "DOLCE かつ富",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "かとむら",
    Id: "katomura",
    Genre: [1],
    Score: [5, 4, 3],
    Distance: 850,
    Opened: [1130, 1430, 1730, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "かとむら 浅間",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["学生証提示でトッピング無料", ""],
  },
  {
    Name: "すき家松本沢村",
    Id: "sukiya",
    Genre: [0],
    Score: [4, 3, 4],
    Distance: 1300,
    Opened: [0, 2400],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "すき家 沢村",
    Pay: [true, true, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "ニボジロー",
    Id: "nibojiro",
    Genre: [1],
    Score: [4, 4, 4],
    Distance: 1100,
    Opened: [1130, 1430, 1730, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "ニボジロー",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "やま本",
    Id: "yamamoto",
    Genre: [0, 1],
    Score: [3, 4, 3],
    Distance: 1100,
    Opened: [1130, 1430, 1730, 2100],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "中華そば やま本",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "ガスト元町店",
    Id: "gasto",
    Genre: [0, 1],
    Score: [4, 4, 3],
    Distance: 1300,
    Opened: [700, 2500],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "ガスト 元町",
    Pay: [true, true, true],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "さくら食堂",
    Id: "sakurashokudo",
    Genre: [0, 1],
    Score: [3, 4, 4],
    Distance: 1400,
    Opened: [1100, 1345, 1730, 1945],
    OpenedDay: [true, true, false, true, true, true, true],
    Map: "さくら食堂 大村",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "鳥さく",
    Id: "torisaku",
    Genre: [0],
    Score: [4, 5, 4],
    Distance: 2600,
    Opened: [1000, 2130],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "鳥さく",
    Pay: [false, true, true],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "美な味",
    Id: "minami",
    Genre: [1],
    Score: [5, 4, 3],
    Distance: 350,
    Opened: [1100, 1500, 1730, 2130],
    OpenedDay: [true, true, false, true, true, true, true],
    Map: "美な味",
    Pay: [false, false, false],
    Parking: [false, true],
    Coupon: ["学生証持参で各種サービス", ""],
  },
  {
    Name: "あさひ",
    Id: "asahi",
    Genre: [4],
    Score: [5, 3, 2],
    Distance: 550,
    Opened: [1800, 2400],
    OpenedDay: [true, true, true, true, true, true, false],
    Map: "お好み焼き あさひ",
    Pay: [false, false, false],
    Parking: [false, false],
    Coupon: ["なし", ""],
  },
  {
    Name: "心 #ism",
    Id: "sin",
    Genre: [5],
    Score: [5, 5, 1],
    Distance: 850,
    Opened: [1700, 2340],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "焼肉 心 桐",
    Pay: [true, true, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "分福",
    Id: "bunpoku",
    Genre: [1],
    Score: [3, 4, 4],
    Distance: 850,
    Opened: [1130, 1345, 1730, 2000],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "分福",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "カトマンズ",
    Id: "katomanzu",
    Genre: [0, 5],
    Score: [4, 5, 3],
    Distance: 600,
    Opened: [1100, 1500, 1700, 2300],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "ウェルカムカトマンズ",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "THE定食屋",
    Id: "theteishokuya",
    Genre: [0],
    Score: [3, 4, 4],
    Distance: 600,
    Opened: [1100, 1430, 1700, 2400],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "THE定食屋",
    Pay: [false, true, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "月のなごみ",
    Id: "tukinonagomi",
    Genre: [4],
    Score: [5, 3, 2],
    Distance: 600,
    Opened: [1700, 2300],
    OpenedDay: [false, true, true, true, true, true, true],
    Map: "月のなごみ",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "U2",
    Id: "utwo",
    Genre: [4],
    Score: [5, 3, 2],
    Distance: 600,
    Opened: [0, 0],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "U2",
    Pay: [null, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "狼煙元町店",
    Id: "noroshi_motomachi",
    Genre: [1],
    Score: [4, 2, 4],
    Distance: 500,
    Opened: [1130, 1430, 1730, 2400],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "狼煙 元町",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "喜本",
    Id: "kimoto",
    Genre: [1],
    Score: [3, 4, 3],
    Distance: 800,
    Opened: [1130, 1500, 1800, 2200], //
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "喜本",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "火和家",
    Id: "hiyoriya",
    Genre: [4],
    Score: [5, 4, 1],
    Distance: 1000,
    Opened: [1800, 2400],
    OpenedDay: [true, true, false, true, true, true, true],
    Map: "火和家",
    Pay: [null, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "ガレージ",
    Id: "garage",
    Genre: [0, 3],
    Score: [5, 2, 3],
    Distance: 1200,
    Opened: [1030, 2030],
    OpenedDay: [true, true, false, false, true, true, true],
    Map: "カフェレストガレージ",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "GREENBASE",
    Id: "greenbase",
    Genre: [3],
    Score: [4, 3, 3],
    Distance: 600,
    Opened: [1130, 2200],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "GREENBASE",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "STARBACKS",
    Id: "starbacks",
    Genre: [3],
    Score: [4, 2, 4],
    Distance: 1700,
    Opened: [900, 2300],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "STARBACKS 東松本",
    Pay: [true, true, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "博多鉄八",
    Id: "teppachi",
    Genre: [1, 4],
    Score: [5, 4, 4],
    Distance: 1700,
    Opened: [1700, 2300],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "鉄八 元町",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "寸八",
    Id: "zunpachi",
    Genre: [1],
    Score: [6, 5, 4],
    Distance: 3400,
    Opened: [1100, 2400],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "寸八",
    Pay: [false, true, false],
    Parking: [true, true],
    Coupon: ["学生証持参で通常より安い学生ラーメンの注文が可能", ""],
  },
  {
    Name: "zun",
    Id: "zun",
    Genre: [1],
    Score: [5, 4, 4],
    Distance: 3000,
    Opened: [1130, 2600],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "zun",
    Pay: [true, true, true],
    Parking: [false, true],
    Coupon: ["学生証持参で通常より安い学生ラーメンの注文が可能", ""],
  },
  {
    Name: "とら",
    Id: "tora",
    Genre: [1],
    Score: [5, 3, 4],
    Distance: 2000,
    Opened: [1100, 1500, 1700, 2000],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "とら",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["学生証持参で大盛り無料", ""],
  },
  {
    Name: "ひづき",
    Id: "hiduki",
    Genre: [1],
    Score: [5, 4, 3],
    Distance: 2100,
    Opened: [1115, 1430, 1815, 2100],
    OpenedDay: [true, false, true, true, true, true, true],
    Map: "ひづき",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "わたりどり",
    Id: "wataridori",
    Genre: [1],
    Score: [5, 4, 3],
    Distance: 3100,
    Opened: [1900, 2730],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "麺心 わたりどり",
    Pay: [false, false, false],
    Parking: [false, false],
    Coupon: ["なし", ""],
  },
  {
    Name: "モスバーガー",
    Id: "mosburger",
    Genre: [3],
    Score: [4, 3, 3],
    Distance: 1300,
    Opened: [900, 2300],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "モスバーガー 松本横田",
    Pay: [false, true, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "とんかつ丸蔵",
    Id: "maruzo",
    Genre: [0, 5],
    Score: [6, 5, 2],
    Distance: 900,
    Opened: [1100, 1400, 1700, 2100],
    OpenedDay: [false, true, true, true, true, true, true],
    Map: "とんかつ 丸蔵",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "弐助",
    Id: "nisuke",
    Genre: [0],
    Score: [4, 4, 4],
    Distance: 2600,
    Opened: [1130, 1430],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "弐助",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "イオンモール松本",
    Id: "aeon",
    Genre: [0, 1, 2, 3],
    Score: [4, 4, 1],
    Distance: 2600,
    Opened: [1000, 2200],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "イオンモール松本",
    Pay: [false, true, true],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "くろべぇ",
    Id: "kurobe",
    Genre: [0],
    Score: [6, 4, 1],
    Distance: 2100,
    Opened: [1130, 1345, 1730, 2045],
    OpenedDay: [false, false, false, true, true, true, true],
    Map: "魚 くろべぇ",
    Pay: [false, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
  {
    Name: "",
    Id: "",
    Genre: [],
    Score: [0, 0, 0],
    Distance: 0,
    Opened: [0, 0],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },

  // 浅間の謎のインド料理や
  // スクールIEの隣の居酒屋
  // スクールIE近くの刀削麺
  // リガーハウス
  // キッチン南海
  // 浅間のカフェ

  {
    Name: "焼肉キング",
    Id: "yakinikuking",
    Genre: [5],
    Score: [0, 0, 0],
    Distance: 2600,
    Opened: [0, 0],
    OpenedDay: [true, true, true, true, true, true, true],
    Map: "",
    Pay: [true, false, false],
    Parking: [true, true],
    Coupon: ["なし", ""],
  },
];

export {
  List,
  changeTime,
  GENRE_COLLECTION,
  PRICE_COLLECTION,
  TIME_COLLECTION,
};
